const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const qml = fs.readFileSync(path.join(__dirname, 'LyricsDaemon.qml'), 'utf8');
// Execute the daemon's actual JavaScript functions without starting a desktop shell.
const functions = [...qml.matchAll(/^    function \w+\([^\n]*\) \{[\s\S]*?^    \}/gm)].map(match => match[0]).join('\n');
const spotify = {identity:'Spotify', dbusName:'org.mpris.MediaPlayer2.spotify', metadata:{'xesam:title':'New song','xesam:artist':['Artist'],'xesam:album':'Album','mpris:length':200000000,'mpris:trackid':'new'}, position:200, length:190, isPlaying:true};
const browser = {identity:'Firefox', dbusName:'org.mpris.MediaPlayer2.firefox.instance_1', metadata:{'xesam:title':'Browser song'}, position:10, isPlaying:true};
const player = spotify;
const root = {offsetMs:0, enabled:true, localDir:'', fetchGeneration:1, activeRequest:null, lastQueryKey:'', spotifyPlayer:spotify};
const state = {value:null, set(value) {this.value=value;}};
const context = {root, MprisController:{availablePlayers:[spotify,browser],activePlayer:browser,bestMetadataPlayer:p=>p,activePlayerStableLength:190}, lyricsState:state, fetchTimeout:{stop(){}},trackDebounce:{stop(){},restart(){}}};
vm.createContext(context);
vm.runInContext(functions, context);
Object.assign(root, Object.fromEntries(Object.keys(context).filter(key => typeof context[key] === 'function').map(key => [key,context[key]])));
assert.equal(context.isSpotify(spotify), true, 'Spotify bus identity is accepted');
assert.equal(context.isSpotify(browser), false, 'browser bus identity is rejected');
assert.equal(context.selectSpotify([browser, spotify]), spotify, 'Spotify is selected independently of active browser');
assert.equal(context.selectSpotify([browser]), null, 'browser-only playback must not select a source');
assert.equal(context.trackMeta(browser).title, '', 'browser metadata cannot reach lyric search');
context.fetchLyrics(browser);
assert.equal(state.value.status, 'idle', 'browser cannot launch a request');
spotify.isPlaying = false;
assert.equal(context.selectSpotify([browser, spotify]), spotify, 'paused Spotify remains selected over playing browser');
spotify.isPlaying = true;
assert.equal(context.trackMeta(player).duration,200, 'metadata snapshot beats stale stable duration');
assert.equal(context.currentPosition(),200,'track end must not wrap to zero');
root.offsetMs=-500;
assert.equal(context.currentPosition(),199.5);
root.offsetMs=0;
const lines=[{start:10,end:15,text:'first'},{start:15,end:20,text:''},{start:20,end:null,text:'second'}];
assert.equal(context.lineAt(lines,5).next,'first');
assert.equal(context.lineAt(lines,16).current,'');
assert.equal(context.lineAt(lines,20).current,'second');
assert.equal(context.lineAt(lines,11).current,'first','seeking backwards must locate the previous line');
const key=context.queryKeyFor(player);
const meta={generation:1,queryKey:key,title:'New song',artist:'Artist'};
const response=JSON.stringify({ok:true,synced:true,lines});
state.value={status:'loading'};
context.handleResponse(response,0,meta);
assert.equal(state.value.status,'ready');
root.enabled=false;
state.value={status:'disabled'};
context.handleResponse(response,0,meta);
assert.equal(state.value.status,'disabled','late success cannot reenable lyrics');
root.enabled=true;
context.cancelRequest();
state.value={status:'loading',title:'Other song'};
context.handleResponse(response,0,meta);
assert.equal(state.value.title,'Other song','cancelled generation cannot overwrite new state');
meta.generation=root.fetchGeneration;
player.metadata['xesam:title']='Other song';
context.handleResponse(response,0,meta);
assert.equal(state.value.status,'loading','identity mismatch must reject response');
player.metadata['xesam:title']='New song';
context.handleResponse('{}',0,meta);
assert.equal(state.value.status,'missing','invalid response is not ready');
console.log('PASS: daemon metadata, seeking, intro/interlude, end position, disabled and stale response regressions');
root.spotifyPlayer = null;
context.scheduleRefresh(true);
assert.equal(state.value.status, 'idle', 'Spotify exit clears lyrics even if browser is playing');
context.handleResponse(response, 0, meta);
assert.equal(state.value.status, 'idle', 'Spotify exit rejects outstanding results');
assert.equal(context.isSpotify({...browser, identity:'Spotify Web Player'}), false);
assert.equal(context.isSpotify({...spotify, dbusName:'org.mpris.MediaPlayer2.spotify.instance42'}), true);
console.log('PASS: Spotify-only selection, browser metadata rejection, paused Spotify and exit lifecycle');
